<?php

namespace Orryv\DockerComposeManager\DockerCompose\CommandExecution;

/**
 * Value object describing the outcome of a docker-compose command execution.
 */
class CommandExecutionResult
{
    private string $id;
    private ?int $pid;
    private string $outputFile;
    private ?string $tmpIdentifier;

    /**
     * @param string $id Identifier for the docker-compose definition.
     * @param int|null $pid Process identifier when available.
     * @param string $outputFile File path to the command output log.
     * @param string|null $tmpIdentifier Temporary identifier derived from the compose file name.
     */
    public function __construct(string $id, ?int $pid, string $outputFile, ?string $tmpIdentifier = null)
    {
        $this->id = $id;
        $this->pid = $pid;
        $this->outputFile = $outputFile;
        $this->tmpIdentifier = $tmpIdentifier;
    }

    /**
     * Identifier for the docker-compose definition.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Retrieve the process identifier if available.
     */
    public function getPid(): ?int
    {
        return $this->pid;
    }

    /**
     * Get the file path of the output log generated by the command execution.
     */
    public function getOutputFile(): string
    {
        return $this->outputFile;
    }

    /**
     * Get the temporary identifier derived from the generated docker-compose file.
     */
    public function getTmpIdentifier(): ?string
    {
        return $this->tmpIdentifier;
    }
}
